// ✅ Static data — replace with axios.get() when API is ready
export const BUILDINGS_DATA = [
  {
    id: 1,
    nameKey: "main",
    floors: 8,
    departments: 12,
    rooms: 95,
    manager: "م. خالد الرشيدي",
    status: "active",
  },
  {
    id: 2,
    nameKey: "emergency",
    floors: 3,
    departments: 4,
    rooms: 38,
    manager: "م. سارة العتيبي",
    status: "active",
  },
  {
    id: 3,
    nameKey: "outpatient",
    floors: 5,
    departments: 8,
    rooms: 60,
    manager: "م. فهد الدوسري",
    status: "active",
  },
  {
    id: 4,
    nameKey: "surgical",
    floors: 4,
    departments: 6,
    rooms: 42,
    manager: "م. منال الغامدي",
    status: "active",
  },
  {
    id: 5,
    nameKey: "maternity",
    floors: 3,
    departments: 5,
    rooms: 34,
    manager: "م. نورة الشهري",
    status: "active",
  },
  {
    id: 6,
    nameKey: "diagnostics",
    floors: 2,
    departments: 3,
    rooms: 20,
    manager: "م. عبدالله المطيري",
    status: "maintenance",
  },
  {
    id: 7,
    nameKey: "admin",
    floors: 4,
    departments: 6,
    rooms: 48,
    manager: "م. ريم القحطاني",
    status: "active",
  },
  {
    id: 8,
    nameKey: "rehab",
    floors: 2,
    departments: 3,
    rooms: 25,
    manager: "م. تركي العسيري",
    status: "inactive",
  },
];