// ✅ Static data — replace with axios.get() when API is ready

export const FLOORS_DATA = [
  {
    id: 1,
    nameKey:   "ground",
    building:  "المبنى الرئيسي",
    occupancy: 75,
    maintenance: 2,
    occupied:    18,
    available:   4,
    depts:       ["الطوارئ", "الاستقبال"],
  },
  {
    id: 2,
    nameKey:   "first",
    building:  "المبنى الرئيسي",
    occupancy: 83,
    maintenance: 1,
    occupied:    25,
    available:   4,
    depts:       ["القلب", "الباطنية"],
  },
  {
    id: 3,
    nameKey:   "second",
    building:  "المبنى الرئيسي",
    occupancy: 71,
    maintenance: 3,
    occupied:    20,
    available:   5,
    depts:       ["الجراحة", "العظام"],
  },
  {
    id: 4,
    nameKey:   "third",
    building:  "المبنى الرئيسي",
    occupancy: 68,
    maintenance: 0,
    occupied:    15,
    available:   7,
    depts:       ["الأطفال", "النساء والولادة"],
  },
  {
    id: 5,
    nameKey:   "first",
    building:  "مبنى العيادات",
    occupancy: 67,
    maintenance: 1,
    occupied:    12,
    available:   5,
    depts:       ["عيادات خارجية"],
  },
  {
    id: 6,
    nameKey:   "second",
    building:  "مبنى العيادات",
    occupancy: 63,
    maintenance: 0,
    occupied:    10,
    available:   6,
    depts:       ["الأشعة", "المختبر"],
  },
];